### ISSUE TITLE
Do we want to add map of Stamford? With or without GPS?

### ISSUE THREAD

**Issue by mcrosby37** [mcrosby37/FlatApp-master#4]

**Comment by simoncar** [comment]
They are re-doing the map over summer, will get a copy of it when done.

**Comment by mcrosby37** [comment]
Nice...


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Simoncar <notifications@github.com> Date: 6/18/17  10:26 AM  (GMT+08:00) To: mcrosby37/FlatApp-master <FlatApp-master@noreply.github.com> Cc: mcrosby37 <mcrosby37@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [mcrosby37/FlatApp-master] Do we want to add map of Stamford? With or without GPS? (#4) 
They are re-doing the map over summer, will get a copy of it when done.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mcrosby37/FlatApp-master","title":"mcrosby37/FlatApp-master","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mcrosby37/FlatApp-master"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simoncar in #4: They are re-doing the map over summer, will get a copy of it when done."}],"action":{"name":"View Issue","url":"https://github.com/mcrosby37/FlatApp-master/issues/4#issuecomment-309252493"}}}
